import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition

def send_email_with_attachment(api_key, recipient_email, subject, content, attachment_path):
    message = Mail(
        from_email='your_email@example.com',
        to_emails=recipient_email,
        subject=subject,
        html_content=content
    )
    
    with open(attachment_path, 'rb') as f:
        data = f.read()
        f.close()
    encoded_file = base64.b64encode(data).decode()

    attachedFile = Attachment(
        FileContent(encoded_file),
        FileName('artifact.zip'),
        FileType('application/zip'),
        Disposition('attachment')
    )
    message.attachment = attachedFile

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e.message)

# Usage example
api_key = os.environ.get('EMAIL_SERVICE_API_KEY')
recipient_email = 'rtblack2701@gamil.com'  # Change to your recipient's email address
subject = 'Your Artifact'
content = '<strong>Attached is the artifact generated by the workflow.</strong>'
attachment_path = 'assets/artifacts'  # Change to the path of your artifact

send_email_with_attachment(api_key, recipient_email, subject, content, attachment_path)
