name: Run Python Script

on:
#   schedule:
#     # Runs at 5 PM UTC every day
#     #- cron: '0 17 * * *'
    workflow_dispatch: # This line enables manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the script
        run: python main.py 
